---
PROXY_DIR: /home/3proxy
MAKE_DIR: /root/3proxy
NDPPD_DIR: /root/ndppd
packages:
  apt:
    all:
      - mc
      - bc
      - bind9
      - nscd
      - git
      - make
      - gcc
    ipv4:
      - python3
      - python3-pip
      - python3-dev
      - python
      - python-pip
  pip:
    ipv4:
      - configobj
sysctl:
  all:
    vm.max_map_count: '95120'
    kernel.threads-max: '240260'
  ipv6:
    net.ipv6.conf.eth0.proxy_ndp: '1'
    net.ipv6.conf.all.proxy_ndp: '1'
    net.ipv6.conf.default.forwarding: '1'
    net.ipv6.conf.all.forwarding: '1'
    net.ipv6.ip_nonlocal_bind: '1'
  ipv4:
    net.ipv4.tcp_tw_reuse: '1'
    net.ipv4.tcp_fin_timeout: '15'
3proxy:
  update: true