 - name: Update cache
   apt:
     update_cache: yes

 - name: Install packages
   apt:
     name: "{{ packages.all }}"
     update_cache: yes
   tags:
   - packages

 - name: Get new kernel
   get_url:
     url: "{{ item }}"
     dest: /root/
   with_items:
     - https://storage.yandexcloud.net/xvostt/linux-headers-4.3.0-040300_4.3.0-040300.201511020949_all.deb
     - https://storage.yandexcloud.net/xvostt/linux-headers-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
     - https://storage.yandexcloud.net/xvostt/linux-image-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
   when: ansible_kernel is version_compare('4','<')
   tags:
   - kernel

 - name: Install a .deb package from the blog.
   apt:
     deb: "{{ item }}"
   with_items:
     - linux-headers-4.3.0-040300_4.3.0-040300.201511020949_all.deb
     - linux-headers-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
     - linux-image-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
   register: update
   when: ansible_kernel is version_compare('4','<')
   tags: kernel

 - name: Reboot to apply new kernel
   reboot:
     reboot_timeout: 120
   when: update is changed and ansible_kernel is version ('4','<')
   tags:
   - kernel

- name: Get git repo 3proxy
   git:
     repo: https://github.com/z3APA3A/3proxy.git
     dest: "{{ MAKE_DIR }}/3proxy"
     version: master

 - name: Make 3proxy
   shell: "cd {{ MAKE_DIR }}/3proxy && make -f Makefile.Linux"
   args:
     executable: /bin/bash
   ignore_errors: true

 - name: Copy 3proxy binary
   shell: "cp -f {{ MAKE_DIR }}/3proxy/bin/3proxy {{ PROXY_DIR }}/3proxy/3proxy"

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'listen-on-v6'
     replace: 'listen-on'
   tags:
   - dns

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'any'
     replace: '127.0.0.1'
   tags:
   - dns

 - name: Change nameservers
   replace:
     path: /etc/network/interfaces
     regexp: '8.8.8.8'
     replace: '127.0.0.1'
   tags:
     - dns

 - name: Copy resolv.conf
   copy:
     src: resolv.conf
     dest: /etc/resolv.conf
     mode: 0744
   tags:
   - dns

 - name: Restart bind9 service
   service:
     name: bind9
     state: restarted
   tags:
   - dns

 - name: Set sysctl values
   sysctl:
     name: "{{ item.key }}"
     value: "{{ item.value }}"
     sysctl_set: yes
   loop: "{{ lookup('dict', sysctl.all) }}"
   tags:
     - sysctl