 - name: Install packages
   apt:
     name: "{{ packages.apt.ipv4 }}"
     update_cache: yes
   tags:
     - apt
     - packages

 - name: Install pip3 packages
   pip:
     name: "{{ packages.pip.ipv4 }}"
     executable: pip3
   tags:
     - pip
     - packages

 - name: Set sysctl values
   sysctl:
     name: "{{ item.key }}"
     value: "{{ item.value }}"
     sysctl_set: yes
   loop: "{{ lookup('dict', sysctl.ipv4) }}"
   tags:
     - sysctl

 - name: Copy script
   template:
     src: setup_ipv4.py
     dest: "{{ PROXY_DIR }}/setup_ipv4.py"
     mode: 0744

 - name: Send config file
   template:
     src: config.ini.j2
     dest: "{{ PROXY_DIR }}/config.ini"
     mode: 0644

 - name: Create 3proxy config
   command: "{{ PROXY_DIR }}/setup_ipv4.py {{ PROXY_DIR }}/config.ini"

 - name: Send systemd .service file
   template:
     src: 3proxy.service.j2
     dest: /etc/systemd/system/3proxy.service
     mode: 0744
   tags: systemd

 - name: start 3proxy.service
   systemd: state=restarted name=3proxy daemon_reload=yes enabled=yes
   tags: systemd
