 - name: Update cache
   apt:
     update_cache: yes

 - name: Install packages
   apt:
     name: "{{ items }}"
     update_cache: yes
   with_items: {{ apt-packages.ipv4 }}
   tags:
   - packages

 - name: Install pip3 packages
   pip:
     name: "{{ item }}"
     executable: pip3
   with_items: {{ pip-packages.ipv4 }}

 - name: Set sysctl values
   sysctl:
     name: "{{ item.key }}"
     value: "{{ item.value }}"
     sysctl_set: yes
   loop: "{{ lookup('dict', sysctl.ipv4) }}"
   tags:
     - sysctl

 - name: Get git repo 3proxy
   git:
     repo: https://github.com/z3APA3A/3proxy.git
     dest: "{{ MAKE_DIR }}/3proxy"
     version: master

 - name: Make 3proxy
   shell: "cd {{ MAKE_DIR }}/3proxy && make -f Makefile.Linux"
   args:
     executable: /bin/bash
   ignore_errors: true

 - name: Copy 3proxy binary
   shell: "cp -f {{ MAKE_DIR }}/3proxy/bin/3proxy {{ PROXY_DIR }}/3proxy/3proxy"

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'listen-on-v6'
     replace: 'listen-on'
   tags:
   - dns

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'any'
     replace: '127.0.0.1'
   tags:
   - dns

 - name: Change nameservers
   replace:
     path: /etc/network/interfaces
     regexp: '8.8.8.8'
     replace: '127.0.0.1'
   tags:
     - dns

 - name: Copy resolv.conf
   copy:
     src: resolv.conf
     dest: /etc/resolv.conf
     mode: 0744
   tags:
   - dns

 - name: Restart bind9 service
   service:
     name: bind9
     state: restarted
   tags:
   - dns

 - name: Copy script
   copy:
     src: scripts/setup_ipv4.py
     dest: "{{ PROXY_DIR }}/setup_ipv4.py"
     mode: 0744

 - name: Send config file
   template:
     src: config.ini.j2
     dest: "{{ PROXY_DIR }}/config.ini"
     mode: 0644

 - name: Create 3proxy config
   shell: "{{ PROXY_DIR }}/setup_ipv4.py ./config.ini"

 - name: Send systemd .service file
   template:
     src: 3proxy.service
     dest: /etc/systemd/system/3proxy.service
     mode: 0744
   tags: systemd

 - name: start 3proxy.service
   systemd: state=restarted name=3proxy daemon_reload=yes enabled=yes
   tags: systemd
