 - name: Update cache
   apt:
     update_cache: yes

 - name: Install packages
   apt:
     name: "{{ items }}"
     update_cache: yes
   with_items: "{{ apt-packages.ipv4 }}"
   tags:
   - packages

 - name: Install pip3 packages
   pip:
     name: "{{ item }}"
     executable: pip3
   with_items: "{{ pip-packages.ipv4 }}"

 - name: Set sysctl values
   sysctl:
     name: "{{ item.key }}"
     value: "{{ item.value }}"
     sysctl_set: yes
   loop: "{{ lookup('dict', sysctl.ipv4) }}"
   tags:
     - sysctl

 - name: Copy script
   copy:
     src: scripts/setup_ipv4.py
     dest: "{{ PROXY_DIR }}/setup_ipv4.py"
     mode: 0744

 - name: Send config file
   template:
     src: config.ini.j2
     dest: "{{ PROXY_DIR }}/config.ini"
     mode: 0644

 - name: Create 3proxy config
   shell: "{{ PROXY_DIR }}/setup_ipv4.py ./config.ini"

 - name: Send systemd .service file
   template:
     src: 3proxy.service
     dest: /etc/systemd/system/3proxy.service
     mode: 0744
   tags: systemd

 - name: start 3proxy.service
   systemd: state=restarted name=3proxy daemon_reload=yes enabled=yes
   tags: systemd
