 - name: Check proxy
   uri:
     url: http://ifconfig.co
     timeout: 5
   register: msg
   environment:
     http_proxy: http://{{ proxy_login }}:{{ proxy_password }}@{{ ansible_host }}:{{ start_port }}
   delegate_to: localhost
   retries: 2
   delay: 10
   when:
     - input == "one" or input is undefined
   tags:
     - check

 - name: Send proxy list
   copy:
     src: "proxylists/{{ ansible_host }}.list"
     dst: "/root/{{ ansible_host }}.list"
     mode: 644
   tags: send_proxy_list